<?php
$file = "C:/xampp/htdocs/Project Besmindo Summary/PRD_SIMOR_BMS.md";
$text = file_get_contents($file);

// Replace Modul 6.3 and 6.4
$pattern = "/### 6\.3 Modul Daily Report.*?(?=### 6\.5 Modul Monthly Report)/s";
$replacement = "### 6.3 Modul Daily Report (Pusat Sentralisasi Log)\n\n#### 6.3.1 Matriks Pekerjaan Sumur\n**URL:** `/daily-report/{rig_id}/{bulan}/{tahun}`\n\nHalaman utama pencatatan per sumur per rig per periode.\n\n**Fitur:**\n- **5 KPI Cards** — Total Sumur, Jam OPS, Jam MIRU, Total Downtime, Tarif ODR Kontrak.\n- **Toolbar Filter Interaktif:**\n  - Selector Rig, Bulan, Tahun.\n  - Live Search sumur/lokasi.\n  - Filter Status: Semua / Completed / Progress.\n  - Tombol Export Excel komprehensif (Quick Export Bundle).\n- **Quick Well Creation (AJAX)** — Tambah sumur \"Moving\" baru langsung dari dropdown form tanpa perlu reload halaman.\n\n#### 6.3.2 Unified Daily Log & The 24-Hour Balance Rule\n**URL:** `/daily-report/log-harian/{rig_id}/{bulan}/{tahun}`\n\nHalaman sentralisasi operasi harian. Menggabungkan pengisian MIRU, OPS, dan seluruh downtime (NPT) dalam satu layar dinamis.\n\n**Fitur:**\n- **The 24-Hour Balance Rule** — Validasi ketat via Javascript. Tombol simpan akan mengunci (disable) dan menampilkan sisa/kelebihan jam sampai total (MIRU + OPS + NPT) tepat 24.0 jam.\n- **Form NPT Dinamis Terintegrasi** — 11 Pos SBWC, 2 Pos UNPAID, dan Breakdown 3rd Party (9 vendor) terintegrasi langsung di layar Daily Report.\n- **Auto-Sync 2 Arah** — Saat log disimpan, sistem otomatis menulis ke tabel `daily_report_log` dan melakukan sinkronisasi breakdown ke tabel `npt_harian` dalam satu transaksi.\n\n---\n\n### 6.4 Modul NPT (Read-Only Dashboard & Analisa)\n\n**URL:** `/npt/{rig_id}/{bulan}/{tahun}`\n\nDahulu merupakan form input yang berat, kini NPT Matrix telah di-upgrade menjadi dashboard analisa visual yang sangat ringan dan informatif.\n\n**Fitur:**\n- **Dashboard Read-Only** — Tidak ada lagi form input atau validasi yang memberatkan. Data NPT ditarik langsung dari sentralisasi Daily Report.\n- **Live Financial Impact Indicator** — Menampilkan metrik *Live Financial Loss* dan *Reliability Drop* secara instan saat pengguna melihat matriks, menghitung kerugian rupiah berdasarkan ODR rig.\n- **Smart Contextual Remark** — Remark UNPAID dan SBWC digabung menjadi satu kolom \"Uraian Detail Kejadian\" yang cerdas.\n- **Matriks Kalender** — Grid tanggal × kategori downtime (1–31 baris, 14+ kolom).\n\n---\n\n";
$text = preg_replace($pattern, $replacement, $text);

// Replace Roadmap
$pattern = "/### Phase 1.*?### Phase 2/s";
$replacement = "### Phase 1 — MVP & Architectural Upgrades (Selesai September 2026)\n\n- [x] Autentikasi (login/logout)\n- [x] Pusat Master Data Terpadu (Rig, Kategori, 3rd Party, Lokasi)\n- [x] Daily Report Step 1 (matriks sumur) + redesign UI\n- [x] Daily Report Quick Well Creation (AJAX modal tanpa reload)\n- [x] UNIFIED DAILY LOG (The 24-Hour Balance Rule) — Sentralisasi form NPT ke dalam Daily Report\n- [x] 3rd Party Breakdown interaktif di dalam Daily Report\n- [x] NPT Harian Matrix Upgrade — Read-Only Dashboard dengan Live Financial Impact & Smart Contextual Remark\n- [x] Monthly Report (KPI otomatis)\n- [x] Rekap Tahunan KPI & NPT (4 mode view)\n- [x] Dashboard dengan Chart.js\n- [x] Export Excel komprehensif (Quick Export Bundle, format SYS)\n- [x] Import data historis 2026 (4,849 sumur, 5,460 logs, 3,392 NPT)\n- [x] Sinkronisasi otomatis 2-arah Log Harian <-> NPT Harian\n\n### Phase 2";
$text = preg_replace($pattern, $replacement, $text);

file_put_contents($file, $text);
echo "Patched successfully!";
?>
